[module/pulseaudio]
type = internal/pulseaudio

; Sink to be used, if it exists (find using `pacmd list-sinks`, name field)
; If not, uses default sink
; sink = alsa_output.pci-0000_12_00.3.analog-stereo

use-ui-max = true
interval = 5
reverse-scroll = false

; Add icon and color indicator for mute status
format-volume = <ramp-volume> <label-volume>
format-muted = <label-muted>

label-volume = " %percentage%%"
label-muted = 󰝟  muted

; Colors (referenced from colors.ini)
label-volume-foreground = ${colors.foreground}
label-muted-foreground = ${colors.alert}

; Optional: ramp for volume levels (icons)
ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 

; Set colors for ramp icons
ramp-volume-foreground = ${colors.primary}

click-right = pavucontrol
