; Add 'temperature' to your bar's modules line, for example:
; modules-right = ... temperature ...

[module/temperature]
type = internal/temperature

; Seconds to sleep between updates
interval = 1

; Thermal zone to use
; Run: for i in /sys/class/thermal/thermal_zone*; do echo "$i: $(<$i/type)"; done
; to find the right zone
thermal-zone = 3

; Base temperature for where to start the ramp (in degrees celsius)
base-temperature = 20

; Threshold temperature to display warning label (in degrees celsius)
warn-temperature = 60

; Whether or not to show units next to the temperature tokens
units = true

; Normal format
format = <ramp> <label>
format-warn = <ramp> <label-warn>

label = %temperature-c%
label-foreground = #e0af68
label-warn = %temperature-c%
label-warn-foreground = #ff757f

; Icons for temperature ramp (low to high)
ramp-0 = 
ramp-1 = 
ramp-2 = 

ramp-0-foreground = #7aa2f7
ramp-1-foreground = #e0af68
ramp-2-foreground = #ff757f